### ISSUE TITLE
OBS completely crashes if the model is not found

### ISSUE THREAD

**Issue by ali1234** [phlash/obs-backscrub#4]
This means you can't get to the settings to change the path to the correct one.

**Comment by phlash** [comment]
Thank you for these fixes - would you like to PR them?

**Comment by ali1234** [comment]
Unfortunately they don't quite work yet. I'll keep trying though.

**Comment by ali1234** [comment]
Okay I see the problem here.

`obs_module_file()` returns a newly allocated string that should be freed with `bfree` (which is `free` but with reference counting, this is how OBS prints the number of memory leaks when you quit.) That is why its return type is `char *`.

`obs_data_get_string()` returns the actual string from the settings, which should not be freed, and that is why its return type is `const char *`.

The code can't know which of these strings is in `filter->modelname` when it is time to free it, so this is a problem. `strdup`'ing everything works, but causes a memory leak in the case where `obs_module_file()` was used.

**Comment by phlash** [comment]
Yep, I vaguely remember reading about the return types and adding the `strdup`, I obviously forgot about reference counted items though! Will take a look at your PR - thanks!
